name: astra_curator
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auto_route: ^3.2.0
  bloc: ^8.0.1
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: 4.0.4
  flash: ^2.0.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.1
  flutter_lints: ^1.0.0
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^0.23.0+1
  freezed_annotation: ^1.0.0
  get_it: ^7.2.0
  highlighter_coachmark: ^0.0.3
  http: ^0.13.4
  image_picker: ^0.8.4+4
  injectable: ^1.5.0
  json_annotation: ^4.4.0
  jwt_decoder: ^2.0.1
  keyboard_dismisser: ^2.0.0
  mask_text_input_formatter: ^2.0.0
  path_provider: ^2.0.7
  pin_code_fields: ^7.3.0
  provider: ^6.0.1
  sembast: ^3.1.1
  shared_preferences: ^2.0.9
  shimmer: ^2.0.0
  outline_gradient_button: ^2.0.0+1
  flutter_cache_manager: ^3.3.0
  flutter_image_compress: ^1.1.0
  meta: ^1.7.0
  image: ^3.1.0
  swipe_cards: ^1.0.0
  flutter_keyboard_visibility: ^5.1.1
  uuid: ^3.0.5
  grouped_list: ^4.2.0
  internet_connection_checker: ^0.0.1+3
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  intl: ^0.17.0
  table_calendar: ^3.0.4
  dart_amqp: ^0.2.1
  mocktail: ^0.3.0
  bloc_test: ^9.0.3

dev_dependencies:
  auto_route_generator: ^3.1.0
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  freezed: ^1.0.2
  injectable_generator: ^1.5.2
  json_serializable: ^6.1.1
  lint: ^1.7.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
